<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/11/01 09:23:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=test2;host=localhost',
  'profiler' => false,
  'username' => 'root',
  'password' => '',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
