<?php
// auto-generated by sfSecurityConfigHandler
// date: 2021/11/01 05:30:01
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'reports_access_tasks',
  ),
  'view' => 
  array (
    'credentials' => 
    array (
    ),
  ),
);
