<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/11/01 05:28:21
sfConfig::add(array(
  'mod_ticketsreports_enabled' => true,
  'mod_ticketsreports_view_class' => 'sfPHP',
));
