<?php
// auto-generated by sfSecurityConfigHandler
// date: 2021/11/08 02:10:41
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
