<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/11/01 05:21:23
sfConfig::add(array(
  'mod_versionsstatus_enabled' => true,
  'mod_versionsstatus_view_class' => 'sfPHP',
));
