<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/11/01 05:21:18
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
