<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/11/01 05:21:33
sfConfig::add(array(
  'mod_discussionsstatus_enabled' => true,
  'mod_discussionsstatus_view_class' => 'sfPHP',
));
