<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/11/01 04:53:31
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
