<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/11/08 02:10:41
sfConfig::add(array(
  'mod_projectsphases_enabled' => true,
  'mod_projectsphases_view_class' => 'sfPHP',
));
