<?php
// auto-generated by sfSecurityConfigHandler
// date: 2021/11/01 04:51:20
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
