<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/11/01 04:51:20
sfConfig::add(array(
  'mod_accessforbidden_enabled' => true,
  'mod_accessforbidden_view_class' => 'sfPHP',
));
