<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/11/01 05:28:15
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
